--!strict
return function()
    return {
        Version = 1,

        --Totals
        TotalKills = 0,
        TotalDeaths = 0,
        TotalWins = 0,
        TotalLosses = 0,
        TotalCoins = 0,
        TotalPlaytime = 0,
        TotalXP = 0,

        --How many this session?
        SessionKills = 0,
        SessionDeaths = 0,
        SessionWins = 0,
        SessionCoins = 0,
        SessionPlaytime = 0,
        SessionXP = 0,
        
        Level = 1,
        Coins = 0,
    }
end
