--!strict

local Types = require(script.Parent.Parent.Parent.Parent.Types)

return {
    Title = "Fireball",
    Description = "Frieren casts a simple yet powerful fireball at an enemy.",
    Cooldown = 5,
    Cost = 50,
    Animation = 95844200176981,
    OnActivate = function()

    end,
    ClientReplication = function()
        
    end,
    Server = function()
        
    end
} :: Types.Ability  